version: '3'
services:
  frontend:
    build:
      context: ./restaurant-application
      dockerfile: ./Dockerfile
    container_name: restaurant_application_frontend
    networks : 
      - restaurant
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./restaurant_application_backend_v1
      dockerfile: ./Dockerfile
    container_name: restaurant_application_backend
    restart : always
    networks : 
      - restaurant
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/restaurant_application_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "5000:5000"
  db:
    image: 'postgres:9.6'
    container_name: db
    networks :
      - restaurant
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=restaurant_application_db
networks :
    restaurant: